#Long term goals are commented out. Just adding them now so I dont have to comb the maps again.

#Levels
pirate_panic_goal      = "Pirate Panic - Goal"
pirate_panic_bonus_1   = "Pirate Panic - Bonus 1"
pirate_panic_bonus_2   = "Pirate Panic - Bonus 2"
pirate_panic_kong      = "Pirate Panic - KONG"
pirate_panic_dk        = "Pirate Panic - DK Coin"
#pirate_panic_1up_1     = "Pirate Panic - 1-Up in Kaptains Kabin"
#pirate_panic_bc_1      = "Pirate Panic - Banana Coin 1"
#pirate_panic_bc_2      = "Pirate Panic - Banana Coin 2"
#pirate_panic_bc_3      = "Pirate Panic - Banana Coin 3"

mainbrace_mayhem_goal    = "Mainbrace Mayhem - Goal"
mainbrace_mayhem_bonus_1 = "Mainbrace Mayhem - Bonus 1"
mainbrace_mayhem_bonus_2 = "Mainbrace Mayhem - Bonus 2"
mainbrace_mayhem_bonus_3 = "Mainbrace Mayhem - Bonus 3"
mainbrace_mayhem_kong    = "Mainbrace Mayhem - KONG"
mainbrace_mayhem_dk      = "Mainbrace Mayhem - DK Coin"
#mainbrace_mayhem_bc_1    = "Mainbrace Mayhem - Banana Coin 1"
#mainbrace_mayhem_bc_2    = "Mainbrace Mayhem - Banana Coin 2"
#mainbrace_mayhem_bc_3    = "Mainbrace Mayhem - Banana Coin 3"

gangplank_galley_goal    = "Gangplank Galley - Goal"
gangplank_galley_bonus_1 = "Gangplank Galley - Bonus 1"
gangplank_galley_bonus_2 = "Gangplank Galley - Bonus 2"
gangplank_galley_kong    = "Gangplank Galley - KONG"
gangplank_galley_dk      = "Gangplank Galley - DK Coin"
#gangplank_galley_bc_1    = "Gangplank Galley - Banana Coin 1"
#gangplank_galley_bc_2    = "Gangplank Galley - Banana Coin 2"
#gangplank_galley_1up_1   = "Gangplank Galley - 1-Up 1"
#gangplank_galley_1up_2   = "Gangplank Galley - 1-Up 2"

lockjaws_locker_goal           = "Lockjaw's Locker - Goal"
lockjaws_locker_bonus_1        = "Lockjaw's Locker - Bonus 1"
lockjaws_locker_kong           = "Lockjaw's Locker - KONG"
lockjaws_locker_dk             = "Lockjaw's Locker - DK Coin"
#lockjaws_locker_bc_1           = "Lockjaw's Locker - Banana Coin 1"
#lockjaws_locker_bc_2           = "Lockjaw's Locker - Banana Coin 2"
#lockjaws_locker_bc_3           = "Lockjaw's Locker - Banana Coin 3"
#lockjaws_locker_bc_4           = "Lockjaw's Locker - Banana Coin 4"
#lockjaws_locker_bc_5           = "Lockjaw's Locker - Banana Coin 5"
#lockjaws_locker_bc_6           = "Lockjaw's Locker - Banana Coin 6"
#lockjaws_locker_bc_7           = "Lockjaw's Locker - Banana Coin 7"
#lockjaws_locker_bc_8           = "Lockjaw's Locker - Banana Coin 8"

topsail_trouble_goal       = "Topsail Trouble - Goal"
topsail_trouble_bonus_1    = "Topsail Trouble - Bonus 1"
topsail_trouble_bonus_2    = "Topsail Trouble - Bonus 2"
topsail_trouble_kong       = "Topsail Trouble - KONG"
topsail_trouble_dk         = "Topsail Trouble - DK Coin"
#topsail_trouble_bc_1       = "Topsail Trouble - Banana Coin 1"
#topsail_trouble_bc_2       = "Topsail Trouble - Banana Coin 2"
#topsail_trouble_1up_1      = "Topsail Trouble - 1-Up 1"
#topsail_trouble_1up_2      = "Topsail Trouble - 1-Up 2"
#topsail_trouble_3up        = "Topsail Trouble - 3-Up"

krows_nest_boss = "Krow's Nest - Boss"
#krows_nest_bc_1 = "Krow's Nest - Banana Coin 1"
#krows_nest_bc_2 = "Krow's Nest - Banana Coin 2"

hothead_hop_goal         = "Hot-Head Hop - Goal"
hothead_hop_bonus_1      = "Hot-Head Hop - Bonus 1"
hothead_hop_bonus_2      = "Hot-Head Hop - Bonus 2"
hothead_hop_bonus_3      = "Hot-Head Hop - Bonus 3"
hothead_hop_kong         = "Hot-Head Hop - KONG"
hothead_hop_dk           = "Hot-Head Hop - DK Coin"
#hothead_hop_2up          = "Hot-Head Hop - 2-Up"
#hothead_hop_bc_1         = "Hot-Head Hop - Banana Coin 1"
#hothead_hop_bc_2         = "Hot-Head Hop - Banana Coin 2"
#hothead_hop_bc_3         = "Hot-Head Hop - Banana Coin 3"
#hothead_hop_bc_4         = "Hot-Head Hop - Banana Coin 4"

kannons_klaim_goal    = "Kannon's Klaim - Goal"
kannons_klaim_bonus_1 = "Kannon's Klaim - Bonus 1"
kannons_klaim_bonus_2 = "Kannon's Klaim - Bonus 2"
kannons_klaim_bonus_3 = "Kannon's Klaim - Bonus 3"
kannons_klaim_kong    = "Kannon's Klaim - KONG"
kannons_klaim_dk      = "Kannon's Klaim - DK Coin"
#kannons_klaim_bc_1    = "Kannon's Klaim - Banana Coin 1"
#kannons_klaim_bc_2    = "Kannon's Klaim - Banana Coin 2"
#kannons_klaim_bc_3    = "Kannon's Klaim - Banana Coin 3"

lava_lagoon_goal         = "Lava Lagoon - Goal"
lava_lagoon_bonus_1      = "Lava Lagoon - Bonus 1"
lava_lagoon_kong         = "Lava Lagoon - KONG"
lava_lagoon_dk           = "Lava Lagoon - DK Coin"
#lava_lagoon_bc_1      = "Lava Lagoon - Banana Coin 1"
#lava_lagoon_bc_2      = "Lava Lagoon - Banana Coin 2"
#lava_lagoon_bc_3      = "Lava Lagoon - Banana Coin 3"
#lava_lagoon_bc_4      = "Lava Lagoon - Banana Coin 4"
#lava_lagoon_bc_5      = "Lava Lagoon - Banana Coin 5"
#lava_lagoon_bc_6      = "Lava Lagoon - Banana Coin 6"
#lava_lagoon_bc_7      = "Lava Lagoon - Banana Coin 7"
#lava_lagoon_bc_8      = "Lava Lagoon - Banana Coin 8"
#lava_lagoon_bc_9      = "Lava Lagoon - Banana Coin 9"
#lava_lagoon_bc_10     = "Lava Lagoon - Banana Coin 10"

redhot_ride_goal      = "Red-Hot Ride - Goal"
redhot_ride_bonus_1   = "Red-Hot Ride - Bonus 1"
redhot_ride_bonus_2   = "Red-Hot Ride - Bonus 2"
redhot_ride_kong      = "Red-Hot Ride - KONG"
redhot_ride_dk        = "Red-Hot Ride - DK Coin"
#redhot_ride_bc_1      = "Red-Hot Ride - Banana Coin - 1"
#redhot_ride_bc_2      = "Red-Hot Ride - Banana Coin - 2"
#redhot_ride_bc_3      = "Red-Hot Ride - Banana Coin - 3"
#redhot_ride_bc_4      = "Red-Hot Ride - Banana Coin - 4"

squaks_shaft_goal = "Squaks's Shaft - Goal"
squaks_shaft_bonus_1 = "Squaks's Shaft - Bonus 1"
squaks_shaft_bonus_2 = "Squaks's Shaft - Bonus 2"
squaks_shaft_bonus_3 = "Squaks's Shaft - Bonus 3"
squaks_shaft_kong = "Squaks's Shaft - KONG"
squaks_shaft_dk = "Squaks's Shaft - DK Coin"
#squaks_shaft_1up_1 = "Squaks's Shaft - 1-Up 1"
#squaks_shaft_bc_1 = "Squaks's Shaft - Banana Coin 1"
#squaks_shaft_bc_2 = "Squaks's Shaft - Banana Coin 2"
#squaks_shaft_bc_3 = "Squaks's Shaft - Banana Coin 3"
#squaks_shaft_bc_4 = "Squaks's Shaft - Banana Coin 4"
#squaks_shaft_bc_5 = "Squaks's Shaft - Banana Coin 5"
#squaks_shaft_bc_6 = "Squaks's Shaft - Banana Coin 6"
#squaks_shaft_bc_7 = "Squaks's Shaft - Banana Coin 7"
#squaks_shaft_bc_8 = "Squaks's Shaft - Banana Coin 8"

kleevers_kiln_boss = "Kleever's Kiln - Boss"
#kleevers_kiln_bc_1 = "Kleever's Kiln - Banana Coin 1"
#kleevers_kiln_bc_2 = "Kleever's Kiln - Banana Coin 2"

barrel_bayou_goal = "Barrel Bayou - Goal"
barrel_bayou_bonus_1 = "Barrel Bayou - Bonus 1"
barrel_bayou_bonus_2 = "Barrel Bayou - Bonus 2"
barrel_bayou_bonus_3 = "Barrel Bayou - Bonus 3"
barrel_bayou_kong = "Barrel Bayou - KONG"
barrel_bayou_dk = "Barrel Bayou - DK Coin"
#barrel_bayou_2up_1 = "Barrel Bayou - 2-Up 1"
#barrel_bayou_bc_1 = "Barrel Bayou - Banana Coin 1"
#barrel_bayou_bc_2 = "Barrel Bayou - Banana Coin 2"
#barrel_bayou_bc_3 = "Barrel Bayou - Banana Coin 3"

glimmers_galleon_goal = "Glimmer's Galleon - Goal"
glimmers_galleon_bonus_1 = "Glimmer's Galleon - Bonus 1"
glimmers_galleon_bonus_2 = "Glimmer's Galleon - Bonus 2"
glimmers_galleon_bonus_3 = "Glimmer's Galleon - Bonus 3"
glimmers_galleon_kong = "Glimmer's Galleon - KONG"
glimmers_galleon_dk = "Glimmer's Galleon - DK Coin"
#glimmers_galleon_1up_1 = "Glimmer's Galleon - 1-Up 1"
#glimmers_galleon_bc_1 = "Glimmer's Galleon - Banana Coin 1"
#glimmers_galleon_bc_2 = "Glimmer's Galleon - Banana Coin 2"
#glimmers_galleon_bc_3 = "Glimmer's Galleon - Banana Coin 3"
#glimmers_galleon_bc_4 = "Glimmer's Galleon - Banana Coin 4"
#glimmers_galleon_bc_5 = "Glimmer's Galleon - Banana Coin 5"
#glimmers_galleon_bc_6 = "Glimmer's Galleon - Banana Coin 6"
#glimmers_galleon_bc_7 = "Glimmer's Galleon - Banana Coin 7"
#glimmers_galleon_bc_8 = "Glimmer's Galleon - Banana Coin 8"
#glimmers_galleon_bc_9 = "Glimmer's Galleon - Banana Coin 9"
#glimmers_galleon_bc_10 = "Glimmer's Galleon - Banana Coin 10"
#glimmers_galleon_bc_11 = "Glimmer's Galleon - Banana Coin 11"

krockhead_klamber_goal = "Krockhead Klamber - Goal"
krockhead_klamber_bonus_1 = "Krockhead Klamber - Bonus 1"
krockhead_klamber_kong = "Krockhead Klamber - KONG"
krockhead_klamber_dk = "Krockhead Klamber - DK Coin"
#krockhead_klamber_1up_1 = "Krockhead Klamber - 1-Up 1"
#krockhead_klamber_3up_1 = "Krockhead Klamber - 3-Up 1"
#krockhead_klamber_bc_1 = "Krockhead Klamber - Banana Coin 1"
#krockhead_klamber_bc_2 = "Krockhead Klamber - Banana Coin 2"
#krockhead_klamber_bc_3 = "Krockhead Klamber - Banana Coin 3"

rattle_battle_goal = "Rattle Battle - Goal"
rattle_battle_bonus_1 = "Rattle Battle - Bonus 1"
rattle_battle_bonus_2 = "Rattle Battle - Bonus 2"
rattle_battle_bonus_3 = "Rattle Battle - Bonus 3"
rattle_battle_kong = "Rattle Battle - KONG"
rattle_battle_dk = "Rattle Battle - DK Coin"
#rattle_battle_bc_1 = "Rattle Battle - Banana Coin 1"
#rattle_battle_bc_2 = "Rattle Battle - Banana Coin 2"

slime_climb_goal = "Slime Climb - Goal"
slime_climb_bonus_1 = "Slime Climb - Bonus 1"
slime_climb_bonus_2 = "Slime Climb - Bonus 2"
slime_climb_kong = "Slime Climb - KONG"
slime_climb_dk = "Slime Climb - DK Coin"
#slime_climb_bc_1 = "Slime Climb - Banana Coin 1"
#slime_climb_bc_2 = "Slime Climb - Banana Coin 2"
#slime_climb_bc_3 = "Slime Climb - Banana Coin 3"

bramble_blast_goal = "Bramble Blast - Goal"
bramble_blast_bonus_1 = "Bramble Blast - Bonus 1"
bramble_blast_bonus_2 = "Bramble Blast - Bonus 2"
bramble_blast_kong = "Bramble Blast - KONG"
bramble_blast_dk = "Bramble Blast - DK Coin"
#bramble_blast_1up_1 = "Bramble Blast - 1-Up 1"
#bramble_blast_bc_1 = "Bramble Blast - Banana Coin 1"
#bramble_blast_bc_2 = "Bramble Blast - Banana Coin 2"

kudgels_kontest_boss = "Kudgel's Kontest - Boss"

hornet_hole_goal = "Hornet Hole - Goal"
hornet_hole_bonus_1 = "Hornet Hole - Bonus 1"
hornet_hole_bonus_2 = "Hornet Hole - Bonus 2"
hornet_hole_bonus_3 = "Hornet Hole - Bonus 3"
hornet_hole_kong = "Hornet Hole - KONG"
hornet_hole_dk = "Hornet Hole - DK Coin"
#hornet_hole_bc_1 = "Hornet Hole - Banana Coin 1"
#hornet_hole_bc_2 = "Hornet Hole - Banana Coin 2"
#hornet_hole_bc_3 = "Hornet Hole - Banana Coin 3"
#chest with unknown contents

target_terror_goal = "Target Terror - Goal"
target_terror_bonus_1 = "Target Terror - Bonus 1"
target_terror_bonus_2 = "Target Terror - Bonus 2"
target_terror_kong = "Target Terror - KONG"
target_terror_dk = "Target Terror - DK Coin"
#target_terror_1up_1 = "Target Terror - 1-Up 1"

bramble_scramble_goal = "Bramble Scramble - Goal"
bramble_scramble_bonus_1 = "Bramble Scramble - Bonus 1"
bramble_scramble_kong = "Bramble Scramble - KONG"
bramble_scramble_dk = "Bramble Scramble - DK Coin"
#bramble_scramble_3up_1 = "Bramble Scramble - 3-Up 1"
#bramble_scramble_bc_1 = "Bramble Scramble - Banana Coin 1"
#bramble_scramble_bc_2 = "Bramble Scramble - Banana Coin 2"
#bramble_scramble_bc_3 = "Bramble Scramble - Banana Coin 3"
#bramble_scramble_bc_4 = "Bramble Scramble - Banana Coin 4"
#bramble_scramble_bc_5 = "Bramble Scramble - Banana Coin 5"
#bramble_scramble_bc_6 = "Bramble Scramble - Banana Coin 6"
#bramble_scramble_bc_7 = "Bramble Scramble - Banana Coin 7"

rickety_race_goal = "Rickety Race - Goal"
rickety_race_bonus_1 = "Rickety Race - Bonus 1"
rickety_race_kong = "Rickety Race - KONG"
rickety_race_dk = "Rickety Race - DK Coin"
#rickety_race_bc_1 = "Rickety Race - Banana Coin 1"

mudhole_marsh_goal = "Mudhole Marsh - Goal"
mudhole_marsh_bonus_1 = "Mudhole Marsh - Bonus 1"
mudhole_marsh_bonus_2 = "Mudhole Marsh - Bonus 2"
mudhole_marsh_kong = "Mudhole Marsh - KONG"
mudhole_marsh_dk = "Mudhole Marsh - DK Coin"
#mudhole_marsh_bc_1 = "Mudhole Marsh - Banana Coin 1"
#mudhole_marsh_bc_2 = "Mudhole Marsh - Banana Coin 2"
#mudhole_marsh_bc_3 = "Mudhole Marsh - Banana Coin 3"
#mudhole_marsh_bc_4 = "Mudhole Marsh - Banana Coin 4"
#mudhole_marsh_bc_5 = "Mudhole Marsh - Banana Coin 5"

rambi_rumble_goal = "Rambi Rumble - Goal"
rambi_rumble_bonus_1 = "Rambi Rumble - Bonus 1"
rambi_rumble_bonus_2 = "Rambi Rumble - Bonus 2"
rambi_rumble_kong = "Rambi Rumble - KONG"
rambi_rumble_dk = "Rambi Rumble - DK Coin"
#rambi_rumble_bc_1 = "Rambi Rumble - Banana Coin 1"
#rambi_rumble_bc_2 = "Rambi Rumble - Banana Coin 2"

king_zing_sting_boss = "King Zing Sting - Boss"
#king_zing_sting_bc_1 = "King Zing Sting - Banana Coin 1"
#king_zing_sting_bc_2 = "King Zing Sting - Banana Coin 2"

ghostly_grove_goal = "Ghostly Grove - Goal"
ghostly_grove_bonus_1 = "Ghostly Grove - Bonus 1"
ghostly_grove_bonus_2 = "Ghostly Grove - Bonus 2"
ghostly_grove_kong = "Ghostly Grove - KONG"
ghostly_grove_dk = "Ghostly Grove - DK Coin"
#ghostly_grove_bc_1 = "Ghostly Grove - Banana Coin 1"
#ghostly_grove_bc_2 = "Ghostly Grove - Banana Coin 2"
#unknown chest content

haunted_hall_goal = "Haunted Hall - Goal"
haunted_hall_bonus_1 = "Haunted Hall - Bonus 1"
haunted_hall_bonus_2 = "Haunted Hall - Bonus 2"
haunted_hall_bonus_3 = "Haunted Hall - Bonus 3"
haunted_hall_kong = "Haunted Hall - KONG"
haunted_hall_dk = "Haunted Hall - DK Coin"
#haunted_hall_bc_1 = "Haunted Hall - Banana Coin 1"
#haunted_hall_bc_2 = "Haunted Hall - Banana Coin 2"
#haunted_hall_bc_3 = "Haunted Hall - Banana Coin 3"

gusty_glade_goal = "Gusty Glade - Goal"
gusty_glade_bonus_1 = "Gusty Glade - Bonus 1"
gusty_glade_bonus_2 = "Gusty Glade - Bonus 2"
gusty_glade_kong = "Gusty Glade - KONG"
gusty_glade_dk = "Gusty Glade - DK Coin"
#gusty_glade_bc_1 = "Gusty Glade - Banana Coin 1"
#gusty_glade_bc_2 = "Gusty Glade - Banana Coin 2"
#gusty_glade_bc_3 = "Gusty Glade - Banana Coin 3"

parrot_chute_panic_goal = "Parrot Chute Panic - Goal"
parrot_chute_panic_bonus_1 = "Parrot Chute Panic - Bonus 1"
parrot_chute_panic_bonus_2 = "Parrot Chute Panic - Bonus 2"
parrot_chute_panic_kong = "Parrot Chute Panic - KONG"
parrot_chute_panic_dk = "Parrot Chute Panic - DK Coin"
#parrot_chute_panic_bc_1 = "Parrot Chute Panic - Banana Coin 1"
#parrot_chute_panic_bc_2 = "Parrot Chute Panic - Banana Coin 2"
#parrot_chute_panic_bc_3 = "Parrot Chute Panic - Banana Coin 3"
#parrot_chute_panic_bc_4 = "Parrot Chute Panic - Banana Coin 4"
#parrot_chute_panic_bc_5 = "Parrot Chute Panic - Banana Coin 5"

web_woods_goal = "Web Woods - Goal"
web_woods_bonus_1 = "Web Woods - Bonus 1"
web_woods_bonus_2 = "Web Woods - Bonus 2"
web_woods_kong = "Web Woods - KONG"
web_woods_dk = "Web Woods - DK Coin"
#web_woods_2up_1 = "Web Woods - 2-Up 1"
#web_woods_2up_2 = "Web Woods - 2-Up 2"
#web_woods_bc_1 = "Web Woods - Banana Coin 1"
#web_woods_bc_2 = "Web Woods - Banana Coin 2"
#web_woods_bc_3 = "Web Woods - Banana Coin 3"
#web_woods_bc_4 = "Web Woods - Banana Coin 4"

kreepy_krow_boss = "Kreepy Krow - Boss"
#kreepy_krow_bc_1 = "Kreepy Krow - Banana Coin 1"
#kreepy_krow_bc_2 = "Kreepy Krow - Banana Coin 2"

artic_abyss_goal = "Artic Abyss - Goal"
artic_abyss_bonus_1 = "Artic Abyss - Bonus 1"
artic_abyss_bonus_2 = "Artic Abyss - Bonus 2"
artic_abyss_kong = "Artic Abyss - KONG"
artic_abyss_dk = "Artic Abyss - DK Coin"
#artic_abyss_1up_1 = "Artic Abyss - 1-Up 1"
#artic_abyss_bc_1 = "Artic Abyss - Banana Coin 1"
#artic_abyss_bc_2 = "Artic Abyss - Banana Coin 2"
#artic_abyss_bc_3 = "Artic Abyss - Banana Coin 3"
#artic_abyss_bc_4 = "Artic Abyss - Banana Coin 4"
#artic_abyss_bc_5 = "Artic Abyss - Banana Coin 5"

windy_well_goal = "Windy Well - Goal"
windy_well_bonus_1 = "Windy Well - Bonus 1"
windy_well_bonus_2 = "Windy Well - Bonus 2"
windy_well_kong = "Windy Well - KONG"
windy_well_dk = "Windy Well - DK Coin"
#windy_well_bc_1 = "Windy Well - Banana Coin 1"
#windy_well_bc_2 = "Windy Well - Banana Coin 2"
#windy_well_bc_3 = "Windy Well - Banana Coin 3"
#windy_well_bc_4 = "Windy Well - Banana Coin 4"

castle_crush_goal = "Castle Crush - Goal"
castle_crush_bonus_1 = "Castle Crush - Bonus 1"
castle_crush_bonus_2 = "Castle Crush - Bonus 2"
castle_crush_kong = "Castle Crush - KONG"
castle_crush_dk = "Castle Crush - DK Coin"
#castle_crush_bc_1 = "Castle Crush - Banana Coin 1"
#castle_crush_bc_2 = "Castle Crush - Banana Coin 2"
#castle_crush_bc_3 = "Castle Crush - Banana Coin 3"

clappers_cavern_goal = "Clapper's Cavern - Goal"
clappers_cavern_bonus_1 = "Clapper's Cavern - Bonus 1"
clappers_cavern_bonus_2 = "Clapper's Cavern - Bonus 2"
clappers_cavern_kong = "Clapper's Cavern - KONG"
clappers_cavern_dk = "Clapper's Cavern - DK Coin"
#clappers_cavern_bc_1 = "Clapper's Cavern - Banana Coin 1"
#clappers_cavern_bc_2 = "Clapper's Cavern - Banana Coin 2"
#clappers_cavern_bc_3 = "Clapper's Cavern - Banana Coin 3"
#clappers_cavern_bc_4 = "Clapper's Cavern - Banana Coin 4"
#clappers_cavern_bc_5 = "Clapper's Cavern - Banana Coin 5"

chain_link_chamber_goal = "Chain Link Chamber - Goal"
chain_link_chamber_bonus_1 = "Chain Link Chamber - Bonus 1"
chain_link_chamber_bonus_2 = "Chain Link Chamber - Bonus 2"
chain_link_chamber_kong = "Chain Link Chamber - KONG"
chain_link_chamber_dk = "Chain Link Chamber - DK Coin"
#chain_link_chamber_bc_1 = "Chain Link Chamber - Banana Coin 1"
#chain_link_chamber_bc_2 = "Chain Link Chamber - Banana Coin 2"
#chain_link_chamber_bc_3 = "Chain Link Chamber - Banana Coin 3"
#chain_link_chamber_bc_4 = "Chain Link Chamber - Banana Coin 4"
#chain_link_chamber_bc_5 = "Chain Link Chamber - Banana Coin 5"

toxic_tower_goal = "Toxic Tower - Goal"
toxic_tower_bonus_1 = "Toxic Tower - Bonus 1"
toxic_tower_kong = "Toxic Tower - KONG"
toxic_tower_dk = "Toxic Tower - DK Coin"
#toxic_tower_2up_1 = "Toxic Tower - 2-Up 1"
#toxic_tower_bc_1 = "Toxic Tower - Banana Coin 1"
#toxic_tower_bc_2 = "Toxic Tower - Banana Coin 2"
#toxic_tower_bc_3 = "Toxic Tower - Banana Coin 3"
#toxic_tower_bc_4 = "Toxic Tower - Banana Coin 4"
#toxic_tower_bc_5 = "Toxic Tower - Banana Coin 5"

stronghold_showdown_goal = "Stronghold Showdown - Goal"
stronghold_showdown_bonus_1 = "Stronghold Showdown - Kremcoin"
#stronghold_showdown_1up_1 = "Stronghold Showdown - 1-Up 1"
#stronghold_showdown_bc_1 = "Stronghold Showdown - Banana Coin 1"
#stronghold_showdown_bc_2 = "Stronghold Showdown - Banana Coin 2"

screechs_sprint_goal = "Screech's Sprint - Goal"
screechs_sprint_bonus_1 = "Screech's Sprint - Bonus 1"
screechs_sprint_kong = "Screech's Sprint - KONG"
screechs_sprint_dk = "Screech's Sprint - DK Coin"
#screechs_sprint_bc_1 = "Screech's Sprint - Banana Coin 1"
#screechs_sprint_bc_2 = "Screech's Sprint - Banana Coin 2"
#screechs_sprint_bc_3 = "Screech's Sprint - Banana Coin 3"
#screechs_sprint_bc_4 = "Screech's Sprint - Banana Coin 4"
#screechs_sprint_bc_5 = "Screech's Sprint - Banana Coin 5"
#screechs_sprint_bc_6 = "Screech's Sprint - Banana Coin 6"
#screechs_sprint_bc_7 = "Screech's Sprint - Banana Coin 7"

krool_duel_boss = "K.Rool Duel - Boss"

jungle_jinx_goal = "Jungle jinx - Goal"
jungle_jinx_kong = "Jungle jinx - KONG"
jungle_jinx_dk = "Jungle jinx - DK Coin"
#jungle_jinx_bc_1 = "Jungle jinx - Banana Coin 1"
#jungle_jinx_bc_2 = "Jungle jinx - Banana Coin 2"
#jungle_jinx_bc_3 = "Jungle jinx - Banana Coin 3"
#jungle_jinx_bc_4 = "Jungle jinx - Banana Coin 4"

black_ice_battle_goal = "Black Ice Battle - Goal"
black_ice_battle_kong = "Black Ice Battle - KONG"
black_ice_battle_dk = "Black Ice Battle - DK Coin"
#black_ice_battle_1up_1 = "Black Ice Battle - 1-Up 1"
#black_ice_battle_1up_2 = "Black Ice Battle - 1-Up 2"
#black_ice_battle_1up_3 = "Black Ice Battle - 1-Up 3"
#black_ice_battle_bc_1 = "Black Ice Battle - Banana Coin 1"

klobber_karnage_goal = "Klobber Karnage - Goal"
klobber_karnage_kong = "Klobber Karnage - KONG"
klobber_karnage_dk = "Klobber Karnage - DK Coin"
klobber_karnage_1up_1 = "Klobber Karnage - 1-Up 1"
#klobber_karnage_bc_1 = "Klobber Karnage - Banana Coin 1"
#klobber_karnage_bc_2 = "Klobber Karnage - Banana Coin 2"
#klobber_karnage_bc_3 = "Klobber Karnage - Banana Coin 3"
#klobber_karnage_bc_4 = "Klobber Karnage - Banana Coin 4"

firey_furnace_goal = "Firey Furnace - Goal"
firey_furnace_kong = "Firey Furnace - KONG"
firey_furnace_dk = "Firey Furnace - DK Coin"
#firey_furnace_bc_1 = "Firey Furnace - Banana Coin 1"
#firey_furnace_bc_2 = "Firey Furnace - Banana Coin 2"

animal_antics_goal = "Animal Antics - Goal"
animal_antics_kong = "Animal Antics - KONG"
animal_antics_dk = "Animal Antics - DK Coin"
animal_antics_1up_1 = "Animal Antics - 1-Up 1"
#animal_antics_bc_1 = "Animal Antics - Banana Coin 1"
#animal_antics_bc_2 = "Animal Antics - Banana Coin 2"
#animal_antics_bc_3 = "Animal Antics - Banana Coin 3"
#animal_antics_bc_4 = "Animal Antics - Banana Coin 4"

krocodile_kore_boss = "Krocodile Kore - Boss"
