#Long term goals are commented out. Just adding them now so I dont have to comb the maps again.

pirate_panic_goal      = "Pirate Panic - Goal"
pirate_panic_bonus_1   = "Pirate Panic - Bonus 1"
pirate_panic_bonus_2   = "Pirate Panic - Bonus 2"
pirate_panic_kong      = "Pirate Panic - KONG"
pirate_panic_dk        = "Pirate Panic - DK Coin"
#pirate_panic_1up_1     = "Pirate Panic - 1-Up in Kaptains Kabin"
#pirate_panic_bc_1      = "Pirate Panic - Banana Coin 1"
#pirate_panic_bc_2      = "Pirate Panic - Banana Coin 2"
#pirate_panic_bc_b1     = "Pirate Panic - Banana Coin in Bonus 1"
#pirate_panic_rambi_1up = "Pirate Panic - Rambi 1-Up"

mainbrace_mayhem_goal    = "Mainbrace Mayhem - Goal"
mainbrace_mayhem_bonus_1 = "Mainbrace Mayhem - Bonus 1"
mainbrace_mayhem_bonus_2 = "Mainbrace Mayhem - Bonus 2"
mainbrace_mayhem_bonus_3 = "Mainbrace Mayhem - Bonus 3"
mainbrace_mayhem_kong    = "Mainbrace Mayhem - KONG"
mainbrace_mayhem_dk      = "Mainbrace Mayhem - DK Coin"
#mainbrace_mayhem_bc_1    = "Mainbrace Mayhem - Banana Coin 1"
#mainbrace_mayhem_bc_2    = "Mainbrace Mayhem - Banana Coin 2"
#mainbrace_mayhem_bc_3    = "Mainbrace Mayhem - Banana Coin 3"
#mainbrace_mayhem_2up     = "Mainbrace Mayhem - 2-Up"

gangplank_galley_goal    = "Gangplank Galley - Goal"
gangplank_galley_bonus_1 = "Gangplank Galley - Bonus 1"
gangplank_galley_bonus_2 = "Gangplank Galley - Bonus 2"
gangplank_galley_kong    = "Gangplank Galley - KONG"
gangplank_galley_dk      = "Gangplank Galley - DK Coin"
#gangplank_galley_bc_1    = "Gangplank Galley - Banana Coin 1"
#gangplank_galley_bc_2    = "Gangplank Galley - Banana Coin 2"
#gangplank_galley_1up_1   = "Gangplank Galley - 1-Up in Chest 1"
#gangplank_galley_1up_2   = "Gangplank Galley - 1-Up in Chest 2"

lockjaws_locker_goal         = "Lockjaw's Locker - Goal"
lockjaws_locker_bonus_1      = "Lockjaw's Locker - Bonus 1"
lockjaws_locker_kong         = "Lockjaw's Locker - KONG"
lockjaws_locker_dk           = "Lockjaw's Locker - DK Coin"
#lockjaws_locker_bc_1         = "Lockjaw's Locker - Banana Coin 1"
#lockjaws_locker_bc_2         = "Lockjaw's Locker - Banana Coin 2"
#lockjaws_locker_bc_3         = "Lockjaw's Locker - Banana Coin 3"
#lockjaws_locker_bc_4         = "Lockjaw's Locker - Banana Coin 4"
#lockjaws_locker_bc_5         = "Lockjaw's Locker - Banana Coin 5"
#lockjaws_locker_bc_6         = "Lockjaw's Locker - Banana Coin 6"
#lockjaws_locker_bc_7         = "Lockjaw's Locker - Banana Coin 7"
#lockjaws_locker_bc_8         = "Lockjaw's Locker - Banana Coin 8"
#lockjaws_locker_enguarde_1up = "Lockjaw's Locker - Enguarde 1-Up"

topsail_trouble_goal       = "Topsail Trouble - Goal"
topsail_trouble_bonus_1    = "Topsail Trouble - Bonus 1"
topsail_trouble_bonus_2    = "Topsail Trouble - Bonus 2"
topsail_trouble_kong       = "Topsail Trouble - KONG"
topsail_trouble_dk         = "Topsail Trouble - DK Coin"
#topsail_trouble_bc_1       = "Topsail Trouble - Banana Coin 1"
#topsail_trouble_bc_2       = "Topsail Trouble - Banana Coin 2"
#topsail_trouble_1up_1      = "Topsail Trouble - 1-Up 1"
#topsail_trouble_1up_2      = "Topsail Trouble - 1-Up 2"
#topsail_trouble_3up        = "Topsail Trouble - 3-Up"
#topsail_trouble_rattly_1up = "Topsail Trouble - Rattly 1-Up"

krows_nest_boss = "Krow's Nest - Boss"
#krows_nest_bc_1 = "Krow's Nest - Banana Coin 1"
#krows_nest_bc_2 = "Krow's Nest - Banana Coin 2"

hothead_hop_goal         = "Hot-Head Hop - Goal"
hothead_hop_bonus_1      = "Hot-Head Hop - Bonus 1"
hothead_hop_bonus_2      = "Hot-Head Hop - Bonus 2"
hothead_hop_bonus_3      = "Hot-Head Hop - Bonus 3"
hothead_hop_kong         = "Hot-Head Hop - KONG"
hothead_hop_dk           = "Hot-Head Hop - DK Coin"
#hothead_hop_2up          = "Hot-Head Hop - 2-Up"
#hothead_hop_bc_1         = "Hot-Head Hop - Banana Coin 1"
#hothead_hop_bc_2         = "Hot-Head Hop - Banana Coin 2"
#hothead_hop_bc_3         = "Hot-Head Hop - Banana Coin 3"
#hothead_hop_bc_4         = "Hot-Head Hop - Banana Coin 4"
#hothead_hop_squitter_1up = "Hot-Head Hop - Squitter 1-Up"

kannons_klaim_goal    = "Kannon's Klaim - Goal"
kannons_klaim_bonus_1 = "Kannon's Klaim - Bonus 1"
kannons_klaim_bonus_2 = "Kannon's Klaim - Bonus 2"
kannons_klaim_bonus_3 = "Kannon's Klaim - Bonus 3"
kannons_klaim_kong    = "Kannon's Klaim - KONG"
kannons_klaim_dk      = "Kannon's Klaim - DK Coin"
#kannons_klaim_bc_1    = "Kannon's Klaim - Banana Coin 1"
#kannons_klaim_bc_2    = "Kannon's Klaim - Banana Coin 2"
#kannons_klaim_bc_3    = "Kannon's Klaim - Banana Coin 3"

lava_lagoon_goal         = "Lava Lagoon - Goal"
lava_lagoon_bonus_1      = "Lava Lagoon - Bonus 1"
lava_lagoon_kong         = "Lava Lagoon - KONG"
lava_lagoon_dk           = "Lava Lagoon - DK Coin"
#lava_lagoon_bc_1      = "Lava Lagoon - Banana Coin 1"
#lava_lagoon_bc_2      = "Lava Lagoon - Banana Coin 2"
#lava_lagoon_bc_3      = "Lava Lagoon - Banana Coin 3"
#lava_lagoon_bc_4      = "Lava Lagoon - Banana Coin 4"
#lava_lagoon_bc_5      = "Lava Lagoon - Banana Coin 5"
#lava_lagoon_bc_6      = "Lava Lagoon - Banana Coin 6"
#lava_lagoon_bc_7      = "Lava Lagoon - Banana Coin 7"
#lava_lagoon_bc_8      = "Lava Lagoon - Banana Coin 8"
#lava_lagoon_bc_9      = "Lava Lagoon - Banana Coin 9"
#lava_lagoon_bc_10     = "Lava Lagoon - Banana Coin 10"
#lava_lagoon_enguarde_1up = "Lava Lagoon - Enguarde 1-Up"

redhot_ride_goal      = "Red-Hot Ride - Goal"
redhot_ride_bonus_1   = "Red-Hot Ride - Bonus 1"
redhot_ride_bonus_2   = "Red-Hot Ride - Bonus 2"
redhot_ride_kong      = "Red-Hot Ride - KONG"
redhot_ride_dk        = "Red-Hot Ride - DK Coin"
#redhot_ride_bc_1      = "Red-Hot Ride - Banana Coin - 1"
#redhot_ride_bc_2      = "Red-Hot Ride - Banana Coin - 2"
#redhot_ride_bc_3      = "Red-Hot Ride - Banana Coin - 3"
#redhot_ride_bc_4      = "Red-Hot Ride - Banana Coin - 4"
#redhot_ride_rambi_1up = "Red-Hot Ride - Rambi 1-Up"
